// autogenerated

export type RequestContext = Partial<Omit<RequestInit>, "method", "body"> & {
  baseUrl?: string;
  fetch?: typeof fetch;
};
type Date = string & { __brand: "date"; };

type Int = number & { __brand: "int"; };

type Uuid = string & { __brand: "uuid"; };

export interface ChangePasswordResponse {
    date: Date;
    details: string;
    name: string;
}

export interface CreateJournalEntryRequest {
    file: File;
    id: Int;
}

export interface JournalEntry {
    createdOn: Date;
    details: string | null;
    id: Uuid;
    status: Int;
    title: string;
    updatedOn: Date;
}

export interface SigninResponse {
    errors: string[];
}

export async function changePassword(oldPassword: string,newPassword: string,ctx?: RequestContext
): Promise<ChangePasswordResponse> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req = {
    ...init,
    method: "POST",
    headers,
  };
  const data = {
    oldPassword,
    newPassword,
  };  headers.set("Content-Type", "application/json");
  req.body = JSON.stringify(data);

  const response = await fetchFn(`${baseUrl}/changePassword`, req);
    return await parseJson<ChangePasswordResponse>(response);


}

export async function createJournalEntry(request: CreateJournalEntryRequest,ctx?: RequestContext
): Promise<JournalEntry> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req = {
    ...init,
    method: "POST",
    headers,
  };
  const data = {
    request,
  };  const body = new FormData();
  const fileMap = {} as Record<string, File>;
  const payload = aliasFiles(data, fileMap);
  body.append("payload", JSON.stringify(payload));
  for (const id in fileMap) {
    body.append(id, fileMap[id]);
  }
  req.body = body;


  const response = await fetchFn(`${baseUrl}/createJournalEntry`, req);
    return await parseJson<JournalEntry>(response);


}

export async function extendSession(ctx?: RequestContext
): Promise<void> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req = {
    ...init,
    method: "POST",
    headers,
  };

  const response = await fetchFn(`${baseUrl}/extendSession`, req);
    return ensureSuccess(response);


}

export async function signin(username: string,password: string,ctx?: RequestContext
): Promise<SigninResponse> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req = {
    ...init,
    method: "POST",
    headers,
  };
  const data = {
    username,
    password,
  };  headers.set("Content-Type", "application/json");
  req.body = JSON.stringify(data);

  const response = await fetchFn(`${baseUrl}/signin`, req);
    return await parseJson<SigninResponse>(response);


}

export async function signout(ctx?: RequestContext
): Promise<void> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req = {
    ...init,
    method: "POST",
    headers,
  };

  const response = await fetchFn(`${baseUrl}/signout`, req);
    return ensureSuccess(response);


}


function aliasFiles<T>(
  input: T,
  map: Record<string, File> = {},
  counter = { i: 0 },
): T {
  if (input instanceof File) {
    const id = `__${counter.i++}`;
    map[id] = input;
    return id as unknown as T;
  }

  if (Array.isArray(input)) {
    return input.map((v) => aliasFiles(v, map, counter)) as unknown as T;
  }

  if (typeof input === "object" && input !== null) {
    return Object.fromEntries(
      Object.entries(input).map(([k, v]) => [k, aliasFiles(v, map, counter)]),
    ) as T;
  }

  return input;
}

async function parseJson<T>(response: Response): Promise<T> {
  ensureSuccess(response);
  return response.json() as Promise<T>;
}

async function ensureSuccess(response: Response) {
  if (!response.ok) {
    const text = await response.text();
    throw new ApiError(response.status, text, response);
  }
}

function resolveContext(ctx?: RequestContext) {
  const { baseUrl, fetch: fetchFn, ...init } = ctx ?? {};
  return {
    baseUrl: baseUrl ?? "",
    fetch: fetchFn ?? fetch,
    init: init ?? {},
  };
}

class ApiError extends Error {
  constructor(
    public status: number,
    public body: string,
    public response: Response
  ) {
    super(`HTTP ${status}: ${body}`);
  }
}