// autogenerated

export type RequestContext = Partial<Omit<RequestInit, "method" | "body">>  & {
  baseUrl?: string;
  fetch?: typeof fetch;
};
type Date = string & { __brand: "date"; };
export const Date = (v: string) => v as Date;

type Int = number & { __brand: "int"; };
export const Int = (v: number) => v as Int;

type Uuid = string & { __brand: "uuid"; };
export const Uuid = (v: string) => v as Uuid;


export const CategoryType = {
  Income: "INCOME",
  Expense: "EXPENSE",
} as const;

export type CategoryType = typeof CategoryType[keyof typeof CategoryType];

export const JournalType = {
  Apples: "APPLES",
  Banans: "BANANS",
  YelloCarrots: "YELLO_CARROTS",
} as const;

export type JournalType = typeof JournalType[keyof typeof JournalType];

export interface ChangePasswordResponse {
    date: Date;
    details: string;
    name: string;
}

export interface CreateJournalEntryRequest {
    fileUri: string;
    id: Int;
    type: JournalType;
}

export interface JournalEntry {
    createdOn: Date;
    details: string | null;
    id: Uuid;
    status: Int;
    title: string;
    updatedOn: Date;
}

export interface SigninResponse {
    errors: string[];
}

export async function changePassword(oldPassword: string,newPassword: string,ctx?: RequestContext
): Promise<ChangePasswordResponse> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req: RequestInit = {
    ...init,
    method: "POST",
    headers,
  };
  const data = {
    oldPassword,
    newPassword,
  };  headers.set("Content-Type", "application/json");
  req.body = JSON.stringify(data);

  const response = await fetchFn(`${baseUrl}/change_password`, req);
    return await parseJson<ChangePasswordResponse>(response);


}

export async function createJournalEntry(request: CreateJournalEntryRequest,ctx?: RequestContext
): Promise<JournalEntry> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req: RequestInit = {
    ...init,
    method: "POST",
    headers,
  };
  const data = {
    request,
  };  headers.set("Content-Type", "application/json");
  req.body = JSON.stringify(data);

  const response = await fetchFn(`${baseUrl}/create_journal_entry`, req);
    return await parseJson<JournalEntry>(response);


}

export async function extendSession(ctx?: RequestContext
): Promise<> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req: RequestInit = {
    ...init,
    method: "POST",
    headers,
  };

  const response = await fetchFn(`${baseUrl}/extend_session`, req);
    return await parseJson<>(response);


}

export async function signin(username: string,password: string,ctx?: RequestContext
): Promise<SigninResponse> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req: RequestInit = {
    ...init,
    method: "POST",
    headers,
  };
  const data = {
    username,
    password,
  };  headers.set("Content-Type", "application/json");
  req.body = JSON.stringify(data);

  const response = await fetchFn(`${baseUrl}/signin`, req);
    return await parseJson<SigninResponse>(response);


}

export async function signout(ctx?: RequestContext
): Promise<> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req: RequestInit = {
    ...init,
    method: "POST",
    headers,
  };

  const response = await fetchFn(`${baseUrl}/signout`, req);
    return await parseJson<>(response);


}


async function parseJson<T>(response: Response): Promise<T> {
  ensureSuccess(response);
  return response.json() as Promise<T>;
}

async function ensureSuccess(response: Response) {
  if (!response.ok) {
    const text = await response.text();
    throw new ApiError(response.status, text, response);
  }
}

function resolveContext(ctx?: RequestContext) {
  const { baseUrl, fetch: fetchFn, ...init } = ctx ?? {};
  return {
    baseUrl: baseUrl ?? "",
    fetch: fetchFn ?? fetch,
    init: init ?? {},
  };
}

class ApiError extends Error {
  constructor(
    public status: number,
    public body: string,
    public response: Response
  ) {
    super(`HTTP ${status}: ${body}`);
  }
}