// autogenerated
type date = string;

type int = number;

type uuid = string;

type ChangePasswordResponse = {
    date: date;
    details: string;
    name: string;
}

type CreateJournalEntryRequest = {
    file: File;
    id: int;
}

type JournalEntry = {
    createdOn: date;
    details: string | null;
    id: uuid;
    status: int;
    title: string;
    updatedOn: date;
}

type SigninResponse = {
    errors: string[];
}

export async function changePassword(oldPassword: string, newPassword: string): Promise<ChangePasswordResponse> {
    const payload = {
        oldPassword,
        newPassword,
    };

    const headers = new Headers();
    const body = JSON.stringify(payload);
    headers.append("Content-Type", "application/json");
    const response = await fetch("/changePassword", {
        method: "POST",
        body,
        headers,
    });

    return await response.json();
}

export async function createJournalEntry(request: CreateJournalEntryRequest): Promise<JournalEntry> {
    const payload = {
        request,
    };

    const headers = new Headers();
    const body = new FormData();
    const fileMap = aliasFiles(payload);
    body.append("payload", JSON.stringify(payload));
    for (const id in fileMap) {
        body.append(id, fileMap[id]);
    }
    const response = await fetch("/createJournalEntry", {
        method: "POST",
        body,
        headers,
    });

    return await response.json();
}

export async function extendSession(): Promise<void> {
    const response = await fetch("/extendSession", {
        method: "POST",
    });

    return await response.json();
}

export async function signin(username: string, password: string): Promise<SigninResponse> {
    const payload = {
        username,
        password,
    };

    const headers = new Headers();
    const body = JSON.stringify(payload);
    headers.append("Content-Type", "application/json");
    const response = await fetch("/signin", {
        method: "POST",
        body,
        headers,
    });

    return await response.json();
}

export async function signout(): Promise<void> {
    const response = await fetch("/signout", {
        method: "POST",
    });

    return await response.json();
}


function aliasFiles(o: any, map: Record<string, File> = {}) {
  let i = 0;
  for (const key in o) {
    if (o[key] instanceof File) {
      const id = `__${i++}`;
      map[id] = o[key];
      o[key] = id;
    } else if (typeof o[key] === "object") {
      aliasFiles(o[key], map);
    }
  }
  return map;
}
