package typescript

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/fireland15/rpc-gen/internal/config"
	"github.com/fireland15/rpc-gen/internal/generators"
	"github.com/fireland15/rpc-gen/internal/model"
	"github.com/iancoleman/strcase"
)

type TypescriptGenerator struct {
	config   TypescriptConfig
	template *template.Template
}

type TypescriptConfig struct {
	Output   string
	Template string
	Types    map[string]typeConfig `json:"types"`
}

type typeConfig struct {
	// The symbol name to import
	Name string `json:"name"`
	// The module string for the import
	Module string `json:"module"`
	// Used when using * as the import
	Default bool `json:"default"`
	// Used when doing something like `import * as Bananas from "apples"`
	Aliasing string `json:"aliasing"`
}

func NewTypescriptGenerator(config config.GeneratorConfig) (generators.CodeGenerator, error) {
	c := new(TypescriptGenerator)

	err := json.Unmarshal(config.Config, &c.config)
	if err != nil {
		return nil, err
	}

	funcs := make(template.FuncMap, 0)
	funcs["resolveType"] = c.resolveType
	funcs["joinParameters"] = func(m model.Method) string {
		params := make([]string, len(m.Parameters))
		for idx, p := range m.Parameters {
			params[idx] = fmt.Sprintf("%s: %s", strcase.ToLowerCamel(p.Name), c.resolveType(p.Type))
		}
		return strings.Join(params, ", ")
	}
	funcs["returnType"] = func(m model.Method) string {
		if m.ReturnType == nil {
			return "void"
		} else {
			return c.resolveType(*m.ReturnType)
		}
	}

	tmpl, err := template.New("ts-client").Funcs(funcs).ParseFiles(c.config.Template)
	if err != nil {
		return nil, err
	}

	c.template = tmpl

	return c, nil
}

func (g *TypescriptGenerator) Generate(service *model.ProtocolDefinition) error {
	err := os.MkdirAll(filepath.Dir(g.config.Output), os.ModePerm)
	if err != nil {
		return err
	}

	f, err := os.Create(g.config.Output)
	if err != nil {
		err = fmt.Errorf("problem opening '%s' (GoEchoServerGenerator): %w", g.config.Output, err)
		return err
	}
	defer f.Close()

	_, err = fmt.Fprintln(f, "// This file is autogenerated. Any changes will be overwritten when regenerated.")
	if err != nil {
		return err
	}

	for _, m := range service.Models {
		err = g.template.ExecuteTemplate(f, "model", m)
		if err != nil {
			return err
		}
	}

	_, err = f.WriteString("type Fetcher<P = unknown, R = unknown> = (url: string, params: P) => Promise<R>;\n")
	if err != nil {
		return err
	}

	for _, m := range service.Methods {
		err = g.template.ExecuteTemplate(f, "method", m)
		if err != nil {
			return err
		}
	}
	return nil
}

func mapToTypescript(sd model.ProtocolDefinition) typescriptCodegen {
	x := typescriptCodegen{}

	// Convert models into typescript types
	for _, m := range sd.Models {
		tsType := model.Model{
			Name:   strcase.ToCamel(m.Name),
			Fields: make([]model.Field, len(m.Fields)),
		}

		for idx, f  := range m.Fields {
			tsType.Fields[idx] = model.Field{
				Name: strcase.ToLowerCamel(f.Name),
				
			}}
		}
	}
	return x
}

func (g *TypescriptGenerator) collectImports(m model.ServiceDefinition) []importStatement {
	importStatements := make([]importStatement, 0)
	for _, model := range m.Models {
		for _, field := range model.Fields {
			rootTypeName(field.Type)
		}
	}
}

func rootTypeName(t model.Type) string {
	if t.Variant == model.TypeVariantNamed {
		return t.Name
	}
	return rootTypeName(*t.Inner)
}

func (g *TypescriptGenerator) resolveType(typeName model.Type) string {
	if typeName.Variant == model.TypeVariantNamed {
		alias, found := g.config.Types[typeName.Name]
		if !found {
			return typeName.Name
		}
		return alias
	} else if typeName.Variant == model.TypeVariantOptional {
		inner := g.resolveType(*typeName.Inner)
		return fmt.Sprintf("%s | null", inner)
	} else if typeName.Variant == model.TypeVariantArray {
		inner := g.resolveType(*typeName.Inner)
		return fmt.Sprintf("%s[]", inner)
	} else {
		panic("unreachable")
	}
}
