// autogenerated

export type RequestContext = Partial<Omit<RequestInit, "method" | "body">>  & {
  baseUrl?: string;
  fetch?: typeof fetch;
};

async function parseJson<T>(response: Response): Promise<T> {
  ensureSuccess(response);
  return response.json() as Promise<T>;
}

async function ensureSuccess(response: Response) {
  if (!response.ok) {
    const text = await response.text();
    throw new ApiError(response.status, text, response);
  }
}

function resolveContext(ctx?: RequestContext) {
  const { baseUrl, fetch: fetchFn, ...init } = ctx ?? {};
  return {
    baseUrl: baseUrl ?? "",
    fetch: fetchFn ?? fetch,
    init: init ?? {},
  };
}

class ApiError extends Error {
  constructor(
    public status: number,
    public body: string,
    public response: Response
  ) {
    super(`HTTP ${status}: ${body}`);
  }
}

function objectToQueryParams(obj: object) {
  const params = new URLSearchParams();

  for (const [key, value] of Object.entries(obj)) {
    if (value === undefined || value === null) continue;

    // Disallow nested objects (but allow arrays)
    if (
      typeof value === "object" &&
      !Array.isArray(value)
    ) {
      throw new Error(
        `Nested objects are not supported for query params (key: "${key}")`
      );
    }

    if (Array.isArray(value)) {
      value.forEach(v => params.append(key, v));
    } else {
      params.append(key, value);
    }
  }

  return params.toString();
}
export type Bool = boolean;

export type Int = number;

export type String = string;

export type Todo = {
  id: Int;
};

export async function changePassword(newPassword: String, oldPassword: String, ctx?: RequestContext): Promise<Bool> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req: RequestInit = {
    ...init,
    method: "POST",
    headers,
  };

  const url = new URL("/change_password", baseUrl);

  const data = {
    newPassword,
    oldPassword,
  }

  headers.set("Content-Type", "application/json");
  req.body = JSON.stringify(data);

  const response = await fetchFn(url.toString(), req);
  return await parseJson<Bool>(response);
}

export async function getTodo(id: Int, ctx?: RequestContext): Promise<Todo> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req: RequestInit = {
    ...init,
    method: "GET",
    headers,
  };

  const url = new URL("/get_todo", baseUrl);

  const data = {
    id,
  }

  const queryParams = objectToQueryParams(data);
  if (queryParams) {
    url.search = queryParams;
  }

  const response = await fetchFn(url.toString(), req);
  return await parseJson<Todo>(response);
}

export async function getTodos(ctx?: RequestContext): Promise<Todo[]> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req: RequestInit = {
    ...init,
    method: "GET",
    headers,
  };

  const url = new URL("/get_todos", baseUrl);

  const response = await fetchFn(url.toString(), req);
  return await parseJson<Todo[]>(response);
}

export async function login(password: String, username: String, ctx?: RequestContext): Promise<void> {
  const { baseUrl, fetch: fetchFn, init } = resolveContext(ctx);

  const headers = new Headers(init?.headers);
  const req: RequestInit = {
    ...init,
    method: "POST",
    headers,
  };

  const url = new URL("/login", baseUrl);

  const data = {
    password,
    username,
  }

  headers.set("Content-Type", "application/json");
  req.body = JSON.stringify(data);

  const response = await fetchFn(url.toString(), req);
  return ensureSuccess(response);
}

